### ISSUE TITLE
Missing peer dependency (@octokit/core@>=3)

### ISSUE THREAD

**Issue by kaiyoma** [octokit/plugin-request-log.js#162]
**What happened?**

When I install lerna in my project, I get this warning during `yarn install`:

```
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.3" has unmet peer dependency "@octokit/core@>=3".
```

**What did you expect to happen?**

No warnings.

**What the problem might be**

Missing peer dependency?

**Comment by gr2m** [comment]
what version of `@octokit/rest` do you use? Make sure you use the latest version

**Comment by kaiyoma** [comment]
Seems like lerna is still pulling in an old version: https://github.com/lerna/lerna/issues/2744

**Comment by gr2m** [comment]
Yes, the problem is related to `@octokit/rest` v16. Starting with v17, `@octokit/rest` is built upon `@octokit/core`, so it's always present. I  cannot fix the problem for `@octokit/rest` v16`. But you should be fine installing `@octokit/core` as dependency in your project to resolve the error
