### ISSUE TITLE
[FEAT]: should 304 conditional requests be logged as errors?

### ISSUE THREAD

**Issue by jeffwilcox** [octokit/plugin-request-log.js#407]
### Describe the need

Not sure if this is a request to "change the default behavior" or "allow some magical flags to customize"...

We make use of conditional requests a lot. We've had to patch the standard Octokit opinionated plugin choices with a version where we treat a `304` `error.status` as informational instead of an error - our server logs were full of all the conditional requests that "successfully" returned 304s.

Not sure if this is something that's come up before, but would love to know how common it is that others do not want to see endless log spew such as this...

```
GET /repos/contosoenterprise/my-test-repo - 304 with id F178:35CFAD:10ED6DE5:100C9A83:6722BC7D in 243ms
```

Just a comment.

### SDK Version

N/A

### API Version

N/A

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
there is no error level logging in this module, it is either log level debug or info

**Comment by jeffwilcox** [comment]
I am specifically looking at this line:

https://github.com/octokit/plugin-request-log.js/blob/268c62891d89b2d4b094bf6c7d179b88baa84842/src/index.ts#L30

```
octokit.log.error(
          `${requestOptions.method} ${path} - ${error.status} with id ${requestId} in ${
            Date.now() - start
          }ms`,
        );
```

This is what we've overridden in our own Octokit scripts to log this as info and not error if `error.status === 304`.

**Comment by wolfy1339** [comment]
The root of this issue is not in this module but rather in `@octokit/request`
https://github.com/octokit/request.js/blob/1ffa99bc99cf465b84079e36a3e04e46b854a7fb/src/fetch-wrapper.ts#L124-L131
We throw an error specifically if the status is a 304

All this plugin does is catch errors from requests and logs them with the error level

**Comment by jeffwilcox** [comment]
OK, fair. We'll just keep patching in our world. Thanks!
